user_config:
  # Quick configuration group for LSM
  exposure-level : "high"
  # 'low'     -> scan rate: '500000.0000', pockel cell gain: 0.30, PMT gain: 0.40
  # 'mid'     -> scan rate: '400000.0000', pockel cell gain: 0.45, PMT gain: 0.45
  # 'high'    -> scan rate: '250000.0000', pockel cell gain: 0.60, PMT gain: 0.50
  # 'extreme' -> scan rate: '200000.0000', pockel cell gain: 0.75, PMT gain: 0.55
  
  snr-level : "low"
  # Estimiated correction according to sample SNR level. Available value: 'low', 'mid', 'high', by default raw data is collected
    
  autofocus-speed : 3
  # Speed of software autofocus, integer: 1~5. Bigger value leads to faster brightfield scan but potentially lower autofocus performance
   
  lsm-resolution : 256
  # LSM scan resolution, available resolution: 256, 512, 1024

  lsm-bin-factor : 15
  # LSM scan pixel average factor, positive integer

  lsm-scan-rate : "250000.0000"
  # LSM scan rate, available value (string): '125000.0000', '200000.0000', '250000.0000','400000.0000', '500000.0000', '625000.0000', '1000000.0000'
    
  lsm-pc-power : 0.4
  # LSM pockel cell gain, float point value: 0.0 ~ 1.0
    
  lsm-pmt-gain : 0.4
  # LSM PMT gain, float point value: 0.0 ~ 1.0
   
  slide-box : [-100, 600, 25500.0, 17000.0] 
  # Pre-define scan area (read out values from the stage): 
  # (start x stage position, start y stage position, end x stage position, end y stage position)
    
  lsm-enhancer : null
  bf-enhancer : null
  classifier : null

model_config:
    gpu : False
    batch-size : 32
    image-channel : 1
    dropout-rate : 0.1
    cnn-base-channel : 4
    normalization : null
    norm-range : [13251, 63085]
    dimension : "2D"
    classifier-backbone : "ResNet18"
    classifier-num-class : 2
    mil-classifier-thresh : 2
    slide-type : "TMA"

hard_config:
    pixel-size-bf-20x : 0.222 # 0.222 micron/pixel at (1392, 1040)
    pixel-size-bf-4x : 1.105 # 1.305 micron/pixel at (1392, 1040)
    pixel-size-shg-base : 0.509 # 0.509 micron/pixel at 256
    pixel-size-shg : 0.509
    camera-resolution : [1392, 1040] # (width, height)
    lsm-resolution-base : [512, 512]
    slide-size : [40000.0, 20000.0] # (width, height) (70000, -20000)
    Z-stage-20x : -6980 # -6930 + 290 / 10500
    Z-stage-laser : -6640 #-6640 
    Z-stage-4x : 3570 # -2300
    F-stage-20x : -15800 # 11000
    F-stage-laser : -18500 # -17500
    F-stage-4x : -1000
    Z-bf-offset : -10560
    Z-laser-offset : 290
    hard-limit-z : [-8500.0, 17000.0]
    hard-limit-x : [-5000.0, 40000.0]
    hard-limit-y : [-4200, 25000.0] #(-2200, 19000.0)
    hard-limit-f : [-19000, 0]
    20x-bf-offset : [-600, 10] # 4x + this value to 20x // (-590, 74)
    shg-offset : [-580, -280] # 4x + this value to shg // (-580, -172)
    led-4x : 4
    led-20x : 5
    focus-device : 'ZStage:Z:32'
    condensor-device : 'ZStage:F:32'
    led-device : ['LED-Dev1ao0', 'Voltage']
    obj-device : ['Turret:O:35', 'Label']